import type { Recurring, Cadence } from "./types";

// ── Local-date helpers (tz-safe; never use toISOString) ──────
function iso(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function parseISO(s: string): Date {
  const [y, m, d] = s.slice(0, 10).split("-").map(Number);
  return new Date(y, (m ?? 1) - 1, d ?? 1);
}
export function todayISO(): string {
  return iso(new Date());
}

/**
 * All occurrence dates a rule should have generated by `today`, excluding any
 * already covered by `last_run`. Returns ISO date strings, oldest first.
 */
export function dueOccurrences(r: Recurring, today = new Date()): string[] {
  if (!r.active) return [];
  const out: string[] = [];
  const todayIso = iso(today);
  const anchor = r.anchor_date.slice(0, 10);
  const after = r.last_run ? r.last_run.slice(0, 10) : null; // strictly greater than

  if (r.cadence === "monthly") {
    const start = parseISO(anchor);
    const dom = r.day_of_month || start.getDate();
    let y = start.getFullYear();
    let m = start.getMonth();
    for (let guard = 0; guard < 600; guard++) {
      const dim = new Date(y, m + 1, 0).getDate();
      const occ = iso(new Date(y, m, Math.min(dom, dim)));
      if (occ > todayIso) break;
      if (occ >= anchor && (!after || occ > after)) out.push(occ);
      if (++m > 11) { m = 0; y++; }
    }
  } else {
    const step = r.cadence === "biweekly" ? 14 : 7;
    let d = parseISO(anchor);
    for (let guard = 0; guard < 1200; guard++) {
      const occ = iso(d);
      if (occ > todayIso) break;
      if (!after || occ > after) out.push(occ);
      d = new Date(d.getFullYear(), d.getMonth(), d.getDate() + step);
    }
  }
  return out;
}

/** The next date this rule will fire, strictly after `today`. */
export function nextOccurrence(r: Recurring, today = new Date()): string {
  const todayIso = iso(today);
  if (r.cadence === "monthly") {
    const dom = r.day_of_month || parseISO(r.anchor_date).getDate();
    let y = today.getFullYear();
    let m = today.getMonth();
    for (let guard = 0; guard < 24; guard++) {
      const dim = new Date(y, m + 1, 0).getDate();
      const occ = iso(new Date(y, m, Math.min(dom, dim)));
      if (occ > todayIso) return occ;
      if (++m > 11) { m = 0; y++; }
    }
  } else {
    const step = r.cadence === "biweekly" ? 14 : 7;
    let d = parseISO(r.anchor_date);
    for (let guard = 0; guard < 2000; guard++) {
      const occ = iso(d);
      if (occ > todayIso) return occ;
      d = new Date(d.getFullYear(), d.getMonth(), d.getDate() + step);
    }
  }
  return todayIso;
}

export function cadenceLabel(c: Cadence): string {
  return c === "monthly" ? "Monthly" : c === "biweekly" ? "Every 2 weeks" : "Weekly";
}
